[package]
name = "concoct"
version = "0.1.0"
edition = "2021"

[lib]
name = "concoct"
path = "src/lib.rs"

[dependencies]
rayon = "1"

[build-dependencies]
cc = "1"

[dev-dependencies]
proptest = "1"
rayon = "1"
num_cpus = "1"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "bench_leaf"
harness = false
