// Input loading: composition (FASTA + k-mer) and coverage (TSV).
//
// Ports concoct/input.py. Each function cites the Python source it replaces.

use std::collections::HashMap;

/// Generate a mapping from k-mer tuples to canonical feature indices.
/// Reverse complement k-mers map to the same index.
///
/// Ports: concoct/input.py generate_feature_mapping (L129-139)
///
/// Returns (mapping, nr_features) where mapping maps k-mer byte strings
/// to their canonical index.
pub fn generate_feature_mapping(kmer_len: usize) -> (HashMap<Vec<u8>, usize>, usize) {
    let complement = |b: u8| -> u8 {
        match b {
            b'A' => b'T',
            b'T' => b'A',
            b'G' => b'C',
            b'C' => b'G',
            _ => unreachable!(),
        }
    };

    let mut kmer_hash: HashMap<Vec<u8>, usize> = HashMap::new();
    let mut counter = 0usize;

    // Iterate over all k-mers in the same order as Python's
    // itertools.product("ATGC", repeat=kmer_len).
    // Rightmost position cycles fastest: AA, AT, AG, AC, TA, ...
    let bases = [b'A', b'T', b'G', b'C'];
    let n_kmers = 4usize.pow(kmer_len as u32);

    for i in 0..n_kmers {
        let kmer: Vec<u8> = (0..kmer_len)
            .map(|pos| {
                let digit = (i / 4usize.pow((kmer_len - 1 - pos) as u32)) % 4;
                bases[digit]
            })
            .collect();

        if !kmer_hash.contains_key(&kmer) {
            kmer_hash.insert(kmer.clone(), counter);
            let rev_compl: Vec<u8> = kmer.iter().rev().map(|&b| complement(b)).collect();
            kmer_hash.insert(rev_compl, counter);
            counter += 1;
        }
    }

    (kmer_hash, counter)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn feature_mapping_kmer2() {
        // For k=2, Python gives 10 canonical features (16 k-mers, 6 pairs of rev-comp).
        let (mapping, nr_features) = generate_feature_mapping(2);
        assert_eq!(nr_features, 10);
        assert_eq!(mapping.len(), 16); // all 16 2-mers present

        // AA and TT are reverse complements → same index
        assert_eq!(mapping[b"AA".as_ref()], mapping[b"TT".as_ref()]);
        // AT is its own reverse complement
        assert_eq!(mapping[b"AT".as_ref()], mapping[b"AT".as_ref()]);
        // GC and GC — also self-complementary
        assert_eq!(mapping[b"GC".as_ref()], mapping[b"GC".as_ref()]);
        // AG and CT are reverse complements
        assert_eq!(mapping[b"AG".as_ref()], mapping[b"CT".as_ref()]);
    }

    #[test]
    fn feature_mapping_kmer4_matches_python() {
        // Compare every k-mer→index pair against the Python reference.
        // Reference generated by: concoct/input.py generate_feature_mapping(4)
        let reference = include_str!("../tests/test_data/feature_mapping_k4.tsv");
        let (mapping, nr_features) = generate_feature_mapping(4);
        assert_eq!(nr_features, 136);

        let mut checked = 0;
        for line in reference.lines() {
            let mut parts = line.split('\t');
            let kmer_str = parts.next().unwrap();
            let expected_idx: usize = parts.next().unwrap().parse().unwrap();

            let kmer_bytes = kmer_str.as_bytes().to_vec();
            let rust_idx = mapping[&kmer_bytes];
            assert_eq!(
                rust_idx, expected_idx,
                "k-mer {kmer_str}: Rust gives {rust_idx}, Python gives {expected_idx}"
            );
            checked += 1;
        }
        assert_eq!(checked, 256, "should check all 256 4-mers");
    }
}
